CREATE TABLE Advogado (
ID_Advogado INTEGER PRIMARY KEY AUTO_INCREMENT,
Senha VARCHAR(3000),
OAB VARCHAR(7),
Login VARCHAR(15),
Nome VARCHAR(50),
img VARCHAR(255)
);
CREATE TABLE cliente (
ID_Cliente INTEGER PRIMARY KEY AUTO_INCREMENT,
Anotacao VARCHAR(255),
Nome VARCHAR(50),
Telefone INTEGER,
CPF INTEGER,
ID_Advogado  INTEGER,
FOREIGN KEY(ID_Advogado ) REFERENCES Advogado (ID_Advogado )
);

CREATE TABLE Plano (
ID_Plano INTEGER PRIMARY KEY AUTO_INCREMENT,
Pagou VARCHAR(10),
Tipo VARCHAR(2),
ID_Advogado  INTEGER,
FOREIGN KEY(ID_Advogado ) REFERENCES Advogado (ID_Advogado )
);

CREATE TABLE Processo (
ID_Processo INTEGER PRIMARY KEY AUTO_INCREMENT,
Numero VARCHAR(25),
Tipo VARCHAR(20),
Parte_contraria VARCHAR(50),
Andamento VARCHAR(50)
);


CREATE TABLE Reclamacao (
ID_Reclamacao INTEGER PRIMARY KEY AUTO_INCREMENT,
Tipo VARCHAR(25),
campo VARCHAR(500)
);
CREATE TABLE Tem (
ID_Processo INTEGER,
ID_Cliente INTEGER,
FOREIGN KEY(ID_Processo) REFERENCES Processo (ID_Processo),
FOREIGN KEY(ID_Cliente) REFERENCES cliente (ID_Cliente)
);

ALTER TABLE Plano ADD FOREIGN KEY(ID_Advogado) REFERENCES Advogado (ID_Advogado);